### ISSUE TITLE
PageTitle in Reader-Module

### ISSUE THREAD

**Issue by rustykowski** [slashworks/contao-simple-job-manager-bundle#1]
Hallo! Beim Testen der Erweiterung fällt mir auf, dass der Seitentitel der Job-Detailseite dem Seitennamen entspricht, nicht dem Jobtitel. Lässt sich das mit Bordmitteln ändern?
Ansonsten ist mein erster Eindruck sehr positiv, danke!

**Comment by Stefanmelz** [comment]
Moin. Ja das ist kein Problem. Ich glaube nur dass das Modul nicht weiter entwickelt wird. Contao geht ja auch einen eigenen Weg in Zukunft, denke wir werden da erneut ansetzen.

**Comment by Stefanmelz** [comment]
habe ich mal ergänzt :)
